const S={step:0,area:[[21,28],[51,19],[80,36],[76,73],[43,83],[18,61]],guide:[],layouts:new Set(['contour']),tool:'polygon',depth:2,speed:.3,direction:0,dx:23,dy:24,scheme:1,generated:false,ranked:false,mode:'support'};
const $=x=>document.querySelector(x),names=['Site & area','Environment','Run simulation','Export results'];
const candidates=[['B','staggered grid',34.7,23,19],['C','staggered grid',34,24,22],['I','aligned grid',33.9,22,22],['A','staggered grid',33.8,22,16]];
const B=(text,action,cls='')=>`<button class="btn ${cls}" data-action="${action}" type="button">${text}</button>`;
function render(){const h=['site','environment','simulation','results'];if(location.hash!==`#${h[S.step]}`)history.replaceState(null,'',`#${h[S.step]}`);$('#steps').innerHTML=names.map((n,i)=>`<button data-step="${i}" class="${S.step===i?'active':''}" ${i===2&&!S.generated||i===3&&!S.ranked?'disabled':''}><span>0${i+1}</span>${n}</button>`).join('');$('#main').innerHTML=[site,env,runScreen,result][S.step]();wire()}
function map(){return `<div class="map map-${S.step}"><span class="maplabel">${S.step===3?'':'Area A · placement boundary'}</span><span class="north">N ↑</span><svg id="drawing" viewBox="0 0 100 100" preserveAspectRatio="none"></svg><span class="scale">0 ━━━━━ ${S.step===3?6:10} m</span><span class="mapcredit">Illustrative terrain</span></div>`}
function mapFoot(){return `<div class="mapfoot"><b>Area A · approx. 420 m²</b><span>Top view · drag points to edit boundary</span></div>`}
function site(){return `<div class="work"><section class="card canvas"><div class="cardhead"><h3>Example seabed · Terrain_01</h3><div class="row">${B('Upload terrain','upload')}${B('3D preview','preview')}</div></div>${map()}${mapFoot()}<input id="file" type="file" hidden accept=".png,.jpg,.jpeg,.svg"></section><section class="card panel sitepanel"><h3>Site & area</h3><h4>DRAW AREA</h4><div class="twocol">${B('Polygon tool','polygon',S.tool==='polygon'?'active':'')}${B('Freehand','freehand',S.tool==='freehand'?'active':'')}</div><h4>EDIT SELECTION</h4>${B('Edit boundary','edit','full '+(S.tool==='edit'?'active':''))}<div class="twocol">${B('Undo','undo')}${B('Redraw','redraw')}</div><p class="instruction">Click points on the map to set the placement area.<br>Drag a point to refine the boundary.</p><div class="selected"><small>Selected area</small><strong>Area A · approx. 420 m²</strong></div></section></div>`}
function field(title,id,value,unit){return `<label class="field">${title}<div class="inputbox"><input type="number" id="${id}" value="${value}" step="0.01"><span>${unit}</span></div></label>`}
function env(){return `<div class="work"><section class="card canvas"><div class="cardhead"><h3>Example seabed · Terrain_01</h3>${B('3D preview','preview')}</div>${map()}${mapFoot()}</section><section class="card panel envpanel"><h3>Environment & design</h3>${field('Water depth','depth',S.depth.toFixed(1),'m')}${field('Current speed','speed',S.speed.toFixed(2),'m/s')}${field('Current direction','direction',S.direction,'°')}<h3 class="layouttitle">Layout pattern</h3><div class="twocol patterns">${[['contour','Contour following'],['aligned','Aligned grid'],['staggered','Staggered grid'],['gully','Gully guide curve']].map(([k,t])=>B(t,'layout:'+k,S.layouts.has(k)?'active':'')).join('')}</div>${S.layouts.has('gully')?`<div class="guidebar"><span>Click map to draw curve</span>${B('Undo','guideUndo')}${B('Clear','guideClear')}</div>`:''}<h4>PLACEMENT SPACING</h4><div class="spacing"><span>Dx / Dy</span><strong>1–1000 cm each</strong></div><div class="spacingfields"><label>Dx<input id="dx" type="number" value="${S.dx}" min="1" max="1000"></label><label>Dy<input id="dy" type="number" value="${S.dy}" min="1" max="1000"></label></div><h4>INDIVIDUAL PARAMETERS</h4><details><summary>7 adjustable ranges <span>⌄</span></summary><p>Support height, width, porosity, anchor depth and spacing</p></details>${B('Generate & evaluate 12 options →','generate','primary generate')}</section></div>`}
function runScreen(){return `<div class="work"><section class="card runscreen"><div class="pill">WORKFLOW DEMO</div><h1>Candidate schemes are ready</h1><div class="percent">100 <span>%</span></div><div class="bar"><i></i></div><p>Demo evaluation complete · review the ranked options below.</p><div class="tasklist">${['Generate layouts & support geometry','Extract mean bed shear stress','Calculate shear stress reduction','Rank and recommend schemes'].map((x,i)=>`<div class="task"><span>0${i+1}</span><strong>${x}</strong><em>Complete</em></div>`).join('')}</div><div class="runbuttons">${B('Back to settings','back')}${B('View ranked schemes →','rank','primary')}</div></section><section class="card summary"><h3>Run summary</h3><div class="heat"></div>${[['Evaluation area','420 m²'],['Water depth',S.depth.toFixed(1)+' m'],['Current speed',S.speed.toFixed(2)+' m/s'],['Current direction',S.direction+'°'],['Candidate schemes','12']].map(([a,b])=>`<div class="summaryrow"><span>${a}</span><strong>${b}</strong></div>`).join('')}<div class="metricnote"><small>EVALUATION METRIC</small><strong>Mean bed shear stress reduction</strong><span>compared with a no-support baseline</span></div></section></div>`}
function result(){let c=candidates[S.scheme];return `<div class="results"><div class="card resulthead"><h2>Compare candidate schemes</h2><div class="row">${B('Edit design','back')}${B('Export CSV','csv')}${B('3D print STL','stl','primary')}</div></div><div class="kpis">${[['Shear stress reduction',c[2].toFixed(1)+'%',`Scheme ${c[0]} · rank ${S.scheme+1} / 12`],['No-support baseline','0.500 Pa','Mean bed shear stress'],['Selected scheme',(.5*(1-c[2]/100)).toFixed(3)+' Pa','Same evaluation area'],['Support count','3','Placed inside Area A']].map(([a,b,d])=>`<div class="card kpi"><small>${a}</small><strong>${b}</strong><span>${d}</span></div>`).join('')}</div><div class="resultgrid"><section class="card scheme"><div class="cardhead"><h3>Scheme ${c[0]} · ${c[1]}</h3><div class="row">${B('Support layout','support',S.mode==='support'?'active':'')}${B('Shear map','shear',S.mode==='shear'?'active':'')}</div></div>${map()}<div class="supportinfo"><strong>Selected support 02</strong><span>X 6.4 m &nbsp; Y 3.1 m</span><p>r 6 cm &nbsp; · &nbsp; d 10 cm &nbsp; · &nbsp; H ${c[4]} cm &nbsp; · &nbsp; n 24 &nbsp; · &nbsp; embedment 15 cm</p></div></section><section class="card ranking"><h3>Candidate ranking</h3><p>Select a scheme to inspect</p>${candidates.map((x,i)=>`<button class="rank ${i===S.scheme?'selected':''}" data-scheme="${i}"><strong>${i===0?'★ ':''}${x[0]} · ${x[1]}</strong><b>${x[2].toFixed(1)}%</b><small>${x[3]} cm spacing · ${x[4]} cm height</small></button>`).join('')}<div class="rankfoot">Export the selected layout and per-support<br>parameters as CSV or printable geometry as STL.<br><b>12 candidates · top 4 shown</b></div></section></div></div>`}
function paint(){let svg=$('#drawing');if(!svg)return;let boundary=S.area.map(p=>p.join(',')).join(' '),guide=S.guide.map(p=>p.join(',')).join(' ');svg.innerHTML=`<polygon class="boundary" points="${boundary}"/>${S.guide.length>1?`<polyline class="guide" points="${guide}"/>`:''}${S.guide.map((p,i)=>`<circle class="handle" data-guide="${i}" cx="${p[0]}" cy="${p[1]}" r="1.3"/>`).join('')}${S.step<2?S.area.map((p,i)=>`<circle class="handle" data-area="${i}" cx="${p[0]}" cy="${p[1]}" r="1.2"/>`).join(''):''}${S.step===3&&S.mode==='support'?[[37,41],[52,47],[64,56]].map(([x,y])=>`<circle class="support" cx="${x}" cy="${y}" r="2.2"/>`).join(''):''}`}
function xy(e){let r=$('#drawing').getBoundingClientRect();return [Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))]}
let drag=null;
function wire(){document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{if(!b.disabled){S.step=+b.dataset.step;render()}});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelectorAll('[data-scheme]').forEach(b=>b.onclick=()=>{S.scheme=+b.dataset.scheme;render()});['depth','speed','direction','dx','dy'].forEach(k=>{let e=$('#'+k);if(e)e.onchange=()=>S[k]=+e.value});let f=$('#file');if(f)f.onchange=()=>{let file=f.files[0];if(file&&file.type.startsWith('image/')){let url=URL.createObjectURL(file);$('.map').style.backgroundImage=`url('${url}')`}};let svg=$('#drawing');if(!svg)return;paint();svg.onpointerdown=e=>{if(e.target.dataset.area!==undefined)drag=['area',+e.target.dataset.area];else if(e.target.dataset.guide!==undefined)drag=['guide',+e.target.dataset.guide];else if(S.step===0&&S.tool!=='edit'){S.area.push(xy(e));paint()}else if(S.step===1&&S.layouts.has('gully')){S.guide.push(xy(e));paint()}if(drag)svg.setPointerCapture(e.pointerId)};svg.onpointermove=e=>{if(drag){S[drag[0]][drag[1]]=xy(e);paint()}};svg.onpointerup=()=>drag=null;svg.onpointercancel=()=>drag=null}
function act(a){if(a.startsWith('layout:')){let k=a.slice(7);S.layouts.has(k)?S.layouts.delete(k):S.layouts.add(k);render();return}if(a==='generate'){if(!S.layouts.size){alert('Select at least one layout pattern.');return}if(S.layouts.has('gully')&&S.guide.length<2){alert('Draw at least two gully curve points on the map.');return}S.generated=true;S.step=2;render();return}if(a==='rank'){S.ranked=true;S.step=3;render();return}if(a==='back'){S.step=1;render();return}if(a==='upload'){$('#file').click();return}if(a==='preview'){alert('3D preview is not available in this demo.');return}if(['polygon','edit','freehand'].includes(a)){S.tool=a;render();return}if(a==='undo'){S.area.pop();render();return}if(a==='redraw'){S.area=[];render();return}if(a==='guideUndo'){S.guide.pop();render();return}if(a==='guideClear'){S.guide=[];render();return}if(a==='support'||a==='shear'){S.mode=a;render();return}if(a==='csv'){let c=candidates[S.scheme];save(`seagrass-${c[0]}.csv`,`scheme,layout,reduction_percent,spacing_cm,height_cm\n${c.join(',')}`,'text/csv');return}if(a==='stl'){let c=candidates[S.scheme];save(`seagrass-${c[0]}.stl`,'solid seagrass\n'+[[0,0],[30,0],[15,26]].map(([x,y])=>cube(x,y,c[4])).join('')+'endsolid seagrass','model/stl')}}
function save(n,s,t){let u=URL.createObjectURL(new Blob([s],{type:t})),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function cube(x,y,h){let p=[[x,y,0],[x+8,y,0],[x+8,y+8,0],[x,y+8,0],[x,y,h],[x+8,y,h],[x+8,y+8,h],[x,y+8,h]],f=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]];return f.map(q=>'facet normal 0 0 0\nouter loop\n'+q.map(i=>'vertex '+p[i].join(' ')).join('\n')+'\nendloop\nendfacet\n').join('')}
window.addEventListener('hashchange',()=>{let i=['#site','#environment','#simulation','#results'].indexOf(location.hash);if(i===2&&!S.generated||i===3&&!S.ranked){render();return}if(i>=0){S.step=i;render()}});render();

